version: '3.5'

services:
  app_proxy:
    environment:
      # <app-id>_<web-container-name>_1
      # e.g. 'btc-rpc-explorer_web_1'
      # Note that the '_1' at the end is needed
      APP_HOST: tubearchivist_web_1
      APP_PORT: 8000
  web:
#    container_name: tubearchivist
    restart: unless-stopped
    image: bbilly1/tubearchivist:v0.4.4@sha256:c96db391d173ae173de53eb5db6fb66e905c48f159d05f8c11d21f1f91178efe
#    ports:
#      - 8000:8000
    volumes:
      - media:/youtube
      - cache:/cache
    environment:
      - ES_URL=http://tubearchivist_es_1:9200     # needs protocol e.g. http and port
      - REDIS_HOST=tubearchivist_redis_1          # don't add protocol
      - HOST_UID=1000
      - HOST_GID=1000
#      - TA_HOST=tubearchivist.local         # set your host name
      - TA_USERNAME=tubearchivist           # your initial TA credentials
      - TA_PASSWORD=umbrel              # your initial TA credentials
      - ELASTIC_PASSWORD=verysecret         # set password for Elasticsearch
      - TZ=Europe/Vienna                 # set your time zone
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - redis
      - es
  redis:
    image: redis/redis-stack-server
#    container_name: archivist-redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - redis:/data
    depends_on:
      - es
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1         # only for amd64, or use official es 8.11.0
#    container_name: archivist-es
    restart: unless-stopped
    environment:
      - "ELASTIC_PASSWORD=verysecret"       # matching Elasticsearch password
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data    # check for permission error when using bind mount, see readme
    expose:
      - "9200"

volumes:
  media:
  cache:
  redis:
  es: