version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: uptime-kuma_server_1
      APP_PORT: 3001

  server:
    image: louislam/uptime-kuma:1.23.7@sha256:1de268eae71a7f126a492fd04e89d4076b2e109eee978e18dabf87bf8a6f6051
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/uptime-kuma:/app/data
